
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import project.dbconnection;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
 public login() {
     initComponents();
          errorlabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        errorlabel = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        passwordbox = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        signupbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        forgotbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jButton10.setText("jButton10");

        jButton5.setText("jButton5");

        errorlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(255, 0, 0));
        errorlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        errorlabel.setText("Incorect Username or Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("POWERED BY CODE X");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 20));

        usernamebox.setBackground(new java.awt.Color(0, 0, 0));
        usernamebox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernamebox.setForeground(new java.awt.Color(51, 51, 51));
        usernamebox.setText("Enter Username");
        usernamebox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usernamebox.setCaretColor(new java.awt.Color(51, 51, 51));
        usernamebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameboxFocusLost(evt);
            }
        });
        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });
        getContentPane().add(usernamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 240, 40));

        passwordbox.setBackground(new java.awt.Color(0, 0, 0));
        passwordbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordbox.setForeground(new java.awt.Color(51, 51, 51));
        passwordbox.setText("Enter Password");
        passwordbox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordbox.setPreferredSize(new java.awt.Dimension(118, 23));
        passwordbox.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        passwordbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordboxFocusLost(evt);
            }
        });
        passwordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordboxActionPerformed(evt);
            }
        });
        getContentPane().add(passwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 240, 40));

        loginbutton.setBackground(new java.awt.Color(0, 0, 0));
        loginbutton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginbutton.setText("Login");
        loginbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.jpg"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, -1));

        signupbutton.setBackground(new java.awt.Color(0, 0, 0));
        signupbutton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(255, 255, 255));
        signupbutton.setText("Signup");
        signupbutton.setBorder(null);
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 100, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("FITNESS HUB");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 100));

        forgotbutton.setBackground(new java.awt.Color(0, 0, 0));
        forgotbutton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        forgotbutton.setForeground(new java.awt.Color(255, 255, 255));
        forgotbutton.setText("Forgot password");
        forgotbutton.setBorder(null);
        forgotbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(forgotbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        setSize(new java.awt.Dimension(635, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void usernameboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameboxFocusGained
       
       
        if(usernamebox.getText().equals("Enter Username"))
        {
            usernamebox.setText("");
            usernamebox.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_usernameboxFocusGained

    private void usernameboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameboxFocusLost
       
       
        if(usernamebox.getText().equals(""))                                  //i did here opposite of above
        {
            usernamebox.setText("Enter Username");
            usernamebox.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_usernameboxFocusLost

    private void passwordboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordboxFocusGained
        //  i do same thing in here
        
        if(passwordbox.getText().equals("Enter Password"))
        {
            passwordbox.setText("");
            passwordbox.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_passwordboxFocusGained

    private void passwordboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordboxFocusLost
        
        errorlabel.setVisible(false);
        if(passwordbox.getText().equals(""))
        {
            passwordbox.setText("Enter Password");
            passwordbox.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_passwordboxFocusLost

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        
         int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit Application","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closebuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

          // get user inpute 
      
        String username = usernamebox.getText();
        String password = passwordbox.getText();
        boolean usernamecorrect = false;
        boolean passwordcorrect = false;   
        
        
         // check user name with database
        
     try {
       Connection   con = dbconnection.getConnection();
          String sql = "SELECT user_name FROM login WHERE user_name=?";          // retrieve the user_name from the login table based on a given username
         PreparedStatement ps = con.prepareCall(sql);
         ps.setString(1, username);
         ResultSet  result = ps.executeQuery();
          
          if(result.next())   {   //Check if there's a row in the result set
              
               usernamecorrect = true;
         
     }else{
              JOptionPane.showMessageDialog(null, "User name is incorrect.. try again","Error",ERROR_MESSAGE);
                
          }
     } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
     }
      
       // check password with database (i do same things in here)
       
          if (usernamecorrect){
              
            try {
               Connection con = dbconnection.getConnection();
                 String sql = "SELECT password FROM login WHERE password=?";
                 PreparedStatement ps = con.prepareCall(sql);
                 ps.setString(1, password);
                 ResultSet result = ps.executeQuery();
                 
                 if (result.next()){ 
                     
                       passwordcorrect=true;
                 }else{
                      JOptionPane.showMessageDialog(null, "Password is incorrect..","Error",ERROR_MESSAGE);
                      
                 }
                 
                //login logic
                
                if (passwordcorrect){
                      home home = new home();
                      home.show();
                      dispose();  
                      JOptionPane.showMessageDialog(null, "login success..");
                }else{
                    JOptionPane.showMessageDialog(null, "Login fail");
                }
                 
                 
            } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null, ex);
            }
                 
                 
          }
         
        
        
        
        
        
   
       
         
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox1.isSelected())
        {
            passwordbox.setEchoChar((char)0);    
        }
        else
        {
            passwordbox.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void passwordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordboxActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);     

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
         new Signup().setVisible(true);
         dispose();
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void forgotbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotbuttonActionPerformed
         new forgot().setVisible(true);
         dispose();
    }//GEN-LAST:event_forgotbuttonActionPerformed

    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameboxActionPerformed

    /**
     * @param args the command line arguments
     */
      

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JButton forgotbutton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JButton signupbutton;
    private javax.swing.JTextField usernamebox;
    // End of variables declaration//GEN-END:variables

    private void forName(String commysqljdbcDriver) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
