import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.dbconnection;



public class Products extends javax.swing.JFrame {

    
    public Products() {
        initComponents();
         try
        {
            int id=1;
            String str1=String.valueOf(id);
            idlebal.setText(str1);
            Connection con=dbconnection.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select max(product_id) from products");
            while(rs.next())   // looping throug the result set
            {
                id=rs.getInt(1); //  coverting to string
                id=id+1;
                String str=String.valueOf(id);
                idlebal.setText(str);
            }
        }
        catch(Exception  e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            Connection con=dbconnection.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from products");
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                
            }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        savebutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        updatebutoon = new javax.swing.JButton();
        idbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amountbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        idlebal = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mfdbox = new javax.swing.JTextField();
        expbox = new javax.swing.JTextField();
        Backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.png"))); // NOI18N
        jLabel1.setText("Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        savebutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        savebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        savebutton.setText("Save");
        savebutton.setToolTipText("");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        searchbutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        deletebutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deletebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        updatebutoon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updatebutoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        updatebutoon.setText("Update");
        updatebutoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebutoonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        idbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 40, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("EXP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MFD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Amount");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        amountbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(amountbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 210, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        namebox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 210, 30));

        idlebal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idlebal.setForeground(new java.awt.Color(255, 0, 0));
        idlebal.setText("00");
        jPanel1.add(idlebal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 30, 20));

        resetbutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resetbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Amount", "Made Date", "Expire Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1000, 260));
        jPanel1.add(mfdbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, -1));

        expbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expboxActionPerformed(evt);
            }
        });
        jPanel1.add(expbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 210, -1));

        Backbutton.setBackground(new java.awt.Color(0, 0, 0));
        Backbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backbutton.setText("<HOME");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        
      
        

        String id=idlebal.getText();
        String name=namebox.getText();
        String amount=amountbox.getText();
        String mfd=mfdbox.getText();   
        String exp=expbox.getText(); 
     
        try
             {
            Connection con=dbconnection.getConnection();
            PreparedStatement ps=con.prepareStatement("insert into products values(?,?,?,?,?)");
            
            ps.setString(1, id);
            ps.setString(2, name );
            ps.setString(3, amount);
            ps.setString(4, mfd);
            ps.setString(5, exp);
        
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Saved");
            setVisible(false);
            new Products().setVisible(true); 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_savebuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
         boolean checkid = false;
        String id=idbox.getText();
        try
        {
            Connection con=dbconnection.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from products where product_id='"+id+"'");
            while(rs.next())
            {
                checkid=true;
                idbox.setEditable(false);
                namebox.setText(rs.getString(2));
                amountbox.setText(rs.getString(1));
                                                                                      
          
            }
            if(checkid==false)
            
                JOptionPane.showMessageDialog(null,"Member ID does not Exit");
            
        }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"Do you really want to Delete","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            String id=idbox.getText();
            try
            {
                Connection con=dbconnection.getConnection();
                Statement st=con.createStatement();
                st.executeUpdate("delete from products where product_id='"+id+"'");
                JOptionPane.showMessageDialog(null,"Successfully Deleted");
                setVisible(false);
                new Products().setVisible(true);
            }
            catch(Exception e)
            {
                 JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void updatebutoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebutoonActionPerformed
        // TODO add your handling code here:
        String id=idbox.getText();
        String name=namebox.getText();
        String amount=amountbox.getText();
        String mfd=mfdbox.getText();
        String exp=expbox.getText();
     
        try
        {
            Connection con=dbconnection.getConnection();
            PreparedStatement ps=con.prepareStatement("update products set name=?,amount=?,made_date=?,expire_date=? where product_id=?");
            ps.setString(1,name);
            ps.setString(2,amount);
            ps.setString(3,mfd);
            ps.setString(4,exp);
            ps.setString(5,id );
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            setVisible(false);
            new equipment().setVisible(true);
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_updatebutoonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Products().setVisible(true);
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void expboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expboxActionPerformed
     
    }//GEN-LAST:event_expboxActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
           new home().setVisible(true);
           dispose();
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JTextField amountbox;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField expbox;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel idlebal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mfdbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton savebutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton updatebutoon;
    // End of variables declaration//GEN-END:variables
}
